[package]
name = "dcm-tools"
version = "0.1.0"
edition = "2024"
[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
dicom = "0.8.1"
tempfile = "3.4"
serde = { version = "1.0.219", features = ["derive"] }
quote = "1.0.40"
syn = { version =  "2.0.101", features = ["full"] }
